### ISSUE TITLE
Add a simple paint tools

### ISSUE THREAD

**Issue by AlexisCaffa** [beatbrot/ScreenshotAssistant#1]
Could be a pencil, a pen, a highlighter pen.. and a simple color picker.

**Comment by beatbrot** [comment]
Definitely have this on my todo-list! Stay tuned for updates :)

**Comment by beatbrot** [comment]
![DrawPreview](https://user-images.githubusercontent.com/1830332/64380381-212bbc00-d031-11e9-9278-cfab78e5ec62.png)

Progress is made! Hope you are still interested :)

**Comment by AlexisCaffa** [comment]
:heart_eyes: thankss

**Comment by beatbrot** [comment]
Just pushed an update containing the draw-tools to F-Droid :) Should be available in 1-2 days
