### ISSUE TITLE
Re-enters About screen instead of taking a screenshot

### ISSUE THREAD

**Issue by JohnVeness** [beatbrot/ScreenshotAssistant#15]
If you enter the About screen, then leave it without pressing back, e.g. by pressing Home, or by clicking on one of the github links, next time you try to make a screenshot (by long pressing Home), the About screen is shown again.

I would argue that if the user has left the About screen by any means (not just by pressing back), then later long presses Home, they are expecting to take a new screenshot, not see the About page again!

**Comment by beatbrot** [comment]
You are definitely correct! I'll try to fix it :)
