### ISSUE TITLE
Store screenshot in PNG format by default

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [beatbrot/ScreenshotAssistant#55]
JPEG usually produce some noises due to its lossy encoding method, which is probably affect the image quality even if this app is set to use the PNG format. If this app use PNG format to store the mage by default while the app is doing capture on screen, it would avoid some visual artifacts around high-contrast areas, also give benifits to users while using PNG and WEBP formats.

See: https://en.wikipedia.org/wiki/Portable_Network_Graphics#Comparison_with_other_file_formats

**Comment by beatbrot** [comment]
Interesting! Thank you for informing me about that :) I didn't know that! :)

**Comment by beatbrot** [comment]
As you can see, I just implemented your suggestion! I hope I get around pushing a new release soon :)
